In [1]:
from sklearn.datasets import make_classification
import torch

In [4]:
X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    random_state=42,
    n_classes=2
)

In [8]:
X.shape

(10, 2)

In [10]:
y.shape

(10,)

In [13]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self,features,labels): 
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self,index): 
        return self.features[index], self.labels[index]

In [14]:
dataset = CustomDataset(X,y)

In [17]:
dataset[2]

(array([-2.8953973 ,  1.97686236]), 0)

In [18]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [21]:
for batch_features, batch_labels in dataloader: 
    print(batch_features)
    print(batch_labels)

tensor([[ 1.0683, -0.9701],
        [-2.8954,  1.9769]], dtype=torch.float64)
tensor([1, 0], dtype=torch.int32)
tensor([[-1.1402, -0.8388],
        [-0.5872, -1.9717]], dtype=torch.float64)
tensor([0, 0], dtype=torch.int32)
tensor([[-0.9382, -0.5430],
        [-0.7206, -0.9606]], dtype=torch.float64)
tensor([1, 0], dtype=torch.int32)
tensor([[1.8997, 0.8344],
        [1.7774, 1.5116]], dtype=torch.float64)
tensor([1, 1], dtype=torch.int32)
tensor([[-1.9629, -0.9923],
        [ 1.7273, -1.1858]], dtype=torch.float64)
tensor([0, 1], dtype=torch.int32)
