In [1]:
import torch
import pandas as pd 

In [2]:
df = pd.read_csv('data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [4]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [5]:
df.shape

(569, 31)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [7]:
scaler = StandardScaler()

In [8]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[-0.82255611, -1.44289106, -0.84545309, ..., -0.87908707,
        -0.04555705, -0.89529703],
       [-0.06023576,  1.21703873,  0.04189701, ...,  0.60516304,
         1.2614201 ,  1.86556003],
       [-0.16873079,  0.53865173, -0.2123995 , ..., -0.02041229,
         0.17722314, -0.69115299],
       ...,
       [ 0.14247864, -1.23308064,  0.10516102, ..., -0.08618182,
        -0.46306364, -0.32871545],
       [-0.85396257, -0.568681  , -0.84338564, ..., -0.5846537 ,
         0.18382404, -0.28996083],
       [-1.19457986, -0.83677209, -1.17086992, ..., -0.72276972,
        -0.63468691,  0.43491425]])

In [10]:
y_train

153    B
501    M
40     M
256    M
391    B
      ..
238    B
210    M
453    B
411    B
524    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self,features,labels): 
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self,index): 
        return self.features[index], self.labels[index]

In [16]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [17]:
train_dataset[1]

(tensor([-0.0602,  1.2170,  0.0419, -0.1422,  1.4701,  1.2264,  0.6127,  0.5231,
          1.7588,  1.3291,  0.2563,  0.5886,  0.0588, -0.0171,  0.9231,  0.7210,
          0.0735,  0.7013,  0.5028,  1.1256, -0.0263,  1.2157, -0.0121, -0.1376,
          2.0997,  0.9430,  0.3285,  0.6052,  1.2614,  1.8656],
        dtype=torch.float64),
 tensor(1, dtype=torch.int32))

In [18]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle= True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle= True)

In [19]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out


In [20]:
learning_rate = 0.1
epochs = 20

In [21]:
loss_function = nn.BCELoss()

In [22]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [23]:
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_train_tensor.dtype

C:\Users\ACER\AppData\Local\Temp\ipykernel_20948\1205825107.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)


torch.float32

In [24]:
y_train_tensor = y_train_tensor.reshape(-1,1)
y_train_tensor = torch.tensor(y_train_tensor, dtype=torch.float32)

C:\Users\ACER\AppData\Local\Temp\ipykernel_20948\2235925388.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor, dtype=torch.float32)


In [26]:
model = MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

#define loop 
for epoch in range(epochs):

    for batch_features, batch_labels in train_loader: 
#forward pass 
        y_pred = model(X_train_tensor)
        
    #loss calculate 
        loss = loss_function(y_pred, y_train_tensor.reshape(-1,1))
    
        optimizer.zero_grad()
    #backward pass 
        loss.backward()
    # parameter update
        optimizer.step()

    
    
        print(f"Epoch:{epoch+1}, Loss: {loss.item()}")

Epoch:1, Loss: 0.7863710522651672
Epoch:1, Loss: 0.5730364322662354
Epoch:1, Loss: 0.4631909430027008
Epoch:1, Loss: 0.3987949788570404
Epoch:1, Loss: 0.3562805950641632
Epoch:1, Loss: 0.32581305503845215
Epoch:1, Loss: 0.30268174409866333
Epoch:1, Loss: 0.2843646705150604
Epoch:1, Loss: 0.26939183473587036
Epoch:1, Loss: 0.25684818625450134
Epoch:1, Loss: 0.24613308906555176
Epoch:1, Loss: 0.23683515191078186
Epoch:1, Loss: 0.22866234183311462
Epoch:1, Loss: 0.2214011400938034
Epoch:1, Loss: 0.21489131450653076
Epoch:2, Loss: 0.20900999009609222
Epoch:2, Loss: 0.20366108417510986
Epoch:2, Loss: 0.19876819849014282
Epoch:2, Loss: 0.19426965713500977
Epoch:2, Loss: 0.1901150643825531
Epoch:2, Loss: 0.18626275658607483
Epoch:2, Loss: 0.18267779052257538
Epoch:2, Loss: 0.1793307662010193
Epoch:2, Loss: 0.1761966347694397
Epoch:2, Loss: 0.17325390875339508
Epoch:2, Loss: 0.1704840362071991
Epoch:2, Loss: 0.1678708791732788
Epoch:2, Loss: 0.16540035605430603
Epoch:2, Loss: 0.163060128688812

In [27]:
model.linear.weight

Parameter containing:
tensor([[ 0.4010,  0.5397,  0.4025,  0.5567,  0.2592,  0.1912,  0.3354,  0.5240,
          0.2162, -0.2865,  0.5506, -0.1959,  0.5437,  0.6132,  0.0643, -0.3539,
         -0.0880,  0.0011, -0.1551, -0.2386,  0.5488,  0.6988,  0.6897,  0.6746,
          0.3850,  0.3606,  0.4064,  0.4487,  0.2468,  0.0328]],
       requires_grad=True)

In [30]:
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

C:\Users\ACER\AppData\Local\Temp\ipykernel_20948\4291323717.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)


torch.float64

In [40]:
model.eval()
accuracy_list = []
with torch.no_grad(): 
    for batch_features, batch_labels in test_loader: 
        batch_features = torch.tensor(batch_features, dtype = torch.float32)
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.5).float()

        batch_accuracy = (y_pred.view(-1)==batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

overall_accuracy = sum(accuracy_list)/len(accuracy_list)
print(overall_accuracy)


0.9626736044883728


C:\Users\ACER\AppData\Local\Temp\ipykernel_20948\639871083.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  batch_features = torch.tensor(batch_features, dtype = torch.float32)
